### ISSUE TITLE
How to use self-password hashing checking policy?

### ISSUE THREAD

**Issue by mickyp** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#10]
Hi, 

I noticed that you comment on the codes related to PasswordEncoder in class SecurityConfiguration. I wonder how the password is validated by the framework since you only provide the UserPrincipalService.

In my case, I try to configure the codes to use my external database that stores the password, but I don't know how to change the validating password policy to check my own password MD5 hashed. Is there any example or documentation I can refer to?

Thanks for your reply in advance.

Sincerely,
Micky

**Comment by mickyp** [comment]
In this method, I didn't see any code regarding validating the password.

```java
 @Transactional
    public UserPrincipal loadUserByUsername(String username) {
        
    	UserPrincipal principal = userPrincipalRepository.getByUsername(username);
       
    	// make sure the authorities and password are loaded
        principal.getAuthorities().size();
        principal.getPassword();
        return principal;
    }
```

But after I ran the application, it DID validate the password and show an error message when the passwords don't match.

Do I need to validate `principal.getPassword();` with my own passwordEncoder?

Sincerely,
Micky

**Comment by Basit-Mahmood** [comment]
@mickyp  Hi,

Right now I don't define any password encoder. But if you look at the `test-data.sql` and `oauth2-registered-client.properties`. Then you can see that I use {bcrypt} and {noop} prefixes. So using this notation Spring know that I have to validate it with bcrypt or no password encoder.  If I define any password encoder bean. Then these prefixes are not necessary.

By default spring uses bcrypt. If you don't define any password encoder bean. And don;t use any prefix and your passwords are not bcrypt encoded. Then spring will complain that password does not match. 

In the earlier version of Spring Authorization Server there was an issue. The password encoder you define in Spring Security Configuration.  Spring Authorization Server was not using it. Like I am using No password encoder bean in my Spring Security configuration. But for Ouath2 registered client spring was using the bcrypt. But now it has been fixed.  That time I put the comment on the code regarding password encoder.

I think either you can use prefix or define a password encoder bean with md5 hash. Hopefully it will work.

Thanks & Regards
Basit Mahmood Ahmed

**Comment by mickyp** [comment]
Hi @Basit-Mahmood ,

Thanks for your kind reply! I will try the suggestions you provided.

Sincerely,
Micky

**Comment by mickyp** [comment]
Hi @Basit-Mahmood,
I wonder if there is a plan to upgrade the related codes affected by the spring-authorization-server 0.3.0 release?

**Comment by Basit-Mahmood** [comment]
@mickyp I will shortly. In fact I have done the changes regarding Spring Boot 2.7.0 and 0.3.0. Testing those changes. Soon I will upgrade it with the latest changes.

Thanks & Regards
Basit Mahmood Ahmed

**Comment by Basit-Mahmood** [comment]
@mickyp It is done. I am closing this issue. We will use new issue if there is any.

Thanks & Regards
Basit Mahmood Ahmed
