### ISSUE TITLE
difference between ClientRegistration and SAS‘s RegisteredClient

### ISSUE THREAD

**Issue by zhenhe** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#13]
is these two the same？

**Comment by Basit-Mahmood** [comment]
@zhenhe Hi. First of all sorry for late reply. Hmm I didn't get you exactly. But are you asking about federated identity and registered client. Like google, github and the clients registered in OAuth2RegisteredClientConfiguration ? 
 
Thanks

**Comment by Basit-Mahmood** [comment]
No response since long time. Closing the issue.
