### ISSUE TITLE
Are there plans to upgrade?

### ISSUE THREAD

**Issue by taolive** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#15]
Are there plans to upgrade?
eg：Spring Boot 3.0.0-RC2

**Comment by Basit-Mahmood** [comment]
@taolive Definitely. I will upgrade it to spring boot 3.0.0 and authorization server 1.0.0. But I am little bit busy these days. Hopefully in first week of December or in the start of second week of December I will upgrade the code. 

But I am thinking that now I will make another repository for Spring Boot 3 and authorization server1.0 and upgrade the current with version 0.4.0. In this way people still using Java 8 and Spring Boot 2 can use it. 

But to your question YES I will. I am very excited to use Spring Boot 3.0 and authorization Server 1.0.0 ;)

**Comment by taolive** [comment]
> 

thanks！

**Comment by taolive** [comment]
@Basit-Mahmood thanks！

**Comment by mickyp** [comment]
@Basit-Mahmood thanks for your work! 

It will be nice if there are two versions including 0.4.0 for Java 8 and 1.0.0 for Java 17.

**Comment by Basit-Mahmood** [comment]
@taolive spring boot 3 and authorization server 1.0.0 has been available in new repository spring-authorization-server-spring-boot-3.

Thanks & Regards
Basit Mahmood Ahmed

**Comment by Basit-Mahmood** [comment]
Upgraded version is available in spring-authorization-server-spring-boot-3 repository
