### ISSUE TITLE
Do you know how to add user detail authorities to the authentication authorities (now only sope in the authorities) 

### ISSUE THREAD

**Issue by Waylon-Firework** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#19]
Hi, thanks for your library. It's helpful. 

Do you know how to add user detail authorities to the authentication authorities (now only sope in the authorities) 

![image](https://user-images.githubusercontent.com/95599645/212241945-42c27cdc-176f-4db3-a947-a89edd613208.png)

**Comment by Waylon-Firework** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/95599645/212242892-16d1aa48-1542-4731-8384-3bf2447c4a32.png">

**Comment by Basit-Mahmood** [comment]
Hi,
Sorry but I didn't understand your question.

**Comment by Basit-Mahmood** [comment]
No response since long time. Closing the issue.
