### ISSUE TITLE
refresh_token not in jwt format

### ISSUE THREAD

**Issue by wxq851685279** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#7]
![image](https://user-images.githubusercontent.com/29041799/149863982-af9b183f-8a63-4e71-937a-25de97f76dc6.png)

**Comment by Basit-Mahmood** [comment]
Hi,
Hope you are doing well. If this is really an issue then please post it to spring authorization server git. This is just a sample project in which password grant type is added. I also try to add some functionality time to time so it can also become sample starter project to configure spring authorization server. If there is some bug in the authorization server. Then please post it to spring authorization server forum.

Thanks

**Comment by Basit-Mahmood** [comment]
If this is a problem. It relates to Core Spring Authorization server. It should be reported to Spring Authorization Server forum.
