### ISSUE TITLE
Support for 0.2.2 - provider is not working anymore 

### ISSUE THREAD

**Issue by vladimir-cirkovic** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#8]
After release of 0.2.2 seems like this is not possible this way anymore, have you checked this upgrade?

Thanks

**Comment by Basit-Mahmood** [comment]
Hi,
What is not working? Password grant type ? I checked after updating to authorization server to 0.2.2 and Password grant type is working. I also updated to latest version 0.2.2 in master too.    Is there any specific case ?  

I updated to latest version of authorization server 0.2.2. Then ran all three projects. Click on the Password grant type and the result came.

**Comment by vladimir-cirkovic** [comment]
Sorry, maybe it's something on my side...

In converter
`Authentication clientPrincipal = SecurityContextHolder.getContext().getAuthentication();`
I have AnonymousAuthenticationToken...
then
provider  fail here `getAuthenticatedClientElseThrowInvalidClient` ...
Which provider fill SecurityContextHolder.getContext().getAuthentication() in you case?
Some of those:
```
						new OAuth2AuthorizationCodeAuthenticationConverter(),
						new OAuth2RefreshTokenAuthenticationConverter(),
						new OAuth2ClientCredentialsAuthenticationConverter(),
```
My request is 	
`POST /oauth/token?grant_type=password&username=test@example.com&password=test&client_id=password-client`

Do you have some hint where potentially, I could have a problem?

**Comment by Basit-Mahmood** [comment]
Hi,

Sorry I couldn't reply to you. I was so busy in some work.

Did your problem solved ?

**Comment by bodruddujach** [comment]
@Basit-Mahmood   Is it possible to provide an example request-response for password grant

**Comment by Basit-Mahmood** [comment]
@bodruddujach Hi. You mean some sort of test case in java. Which use password grant type support to get the response ?

**Comment by Basit-Mahmood** [comment]
This version is too old now. For newer version there is no such problem report. Closing this issue.
