### ISSUE TITLE
I need some help?

### ISSUE THREAD

**Issue by zwjsexcalibur** [Basit-Mahmood/spring-authorization-server-password-grant-type-support#9]
hi,I have learned from your project so much .But I confused by how to logout. could you have some ideal about logout all the clients,when any client logout?thanks.

**Comment by Basit-Mahmood** [comment]
Hi

Sorry I couldn't reply to you. I was so busy in some work.

To be very honest I don't know right now how to do single logout. But I remember I found something about single logout when I was trying to configure Spring Authorization server before the release.  But I don't recall it.

I think there is a CAS server. Central Authentication Service. I used it long time ago. It provides Single sign on and single logout. May be you can look into it.

Sorry again.  But if you have solved it please let me know. It will be beneficial for me and others too.

Thanks

**Comment by Basit-Mahmood** [comment]
@zwjsexcalibur did you achieve it ?

**Comment by Basit-Mahmood** [comment]
No response since long time. Closing the issue.
